title       = "ukparliament"
baseURL     = "https://ukparliament-cli.tamnd.com/"
description = "A command line for ukparliament."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/ukparliament-cli"
